DoAnTMDT/ViewModels/DisplayProductsViewComponent.cs
using DoAnTMDT.DbContext;
using DoAnTMDT.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DoAnTMDT.ViewModels
{
    public class DisplayProductsViewComponent : ViewComponent
    {
        private readonly DoAnTMDT_Entities _context;
        public DisplayProductsViewComponent(DoAnTMDT_Entities context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke(int currentPage = 1)
        {
            return View("_ShowProduct", GetItemsAsync(currentPage));

        }


        private IEnumerable<Product> GetItemsAsync(int currentPage = 1)
        {
            int itemToDisplay = 8;
            int itemToSkip = (currentPage - 1) * itemToDisplay;
            return _context.ProductTable.Skip(itemToSkip).Take(itemToDisplay).ToList();
        }
    }
}

DoAnTMDT/ViewModels/TrackCartViewModel.cs
using DoAnTMDT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DoAnTMDT.ViewModels
{
    public class TrackCartViewModel
    {
        public IEnumerable<Cart> CompletedOrders { get; }
        public IEnumerable<Cart> InCompletedOrders { get; }

        public TrackCartViewModel(IEnumerable<Cart> completedOrders, IEnumerable<Cart> inCompletedOrders)
        {
            CompletedOrders = completedOrders;
            InCompletedOrders = inCompletedOrders;
        }
    }
}

DoAnTMDT/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using DoAnTMDT.Models;
using DoAnTMDT.DbContext;
using DoAnTMDT.Sevices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using PayPal.Core;
using PayPal.v1.Payments;
using Microsoft.EntityFrameworkCore;
using BraintreeHttp;
using System;
using DoAnTMDT.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace DoAnTMDT.Controllers
{
    public class HomeController : Controller
    {
        private readonly CookieServices _cookieServices;
        private readonly DoAnTMDT_Entities _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly string _clientID;
        private readonly string _secretID;


        public HomeController(CookieServices cookieServices, DoAnTMDT_Entities context, IConfiguration config, UserManager<ApplicationUser> userManager)
        {
            _cookieServices = cookieServices;
            _userManager = userManager;
            _context = context;
            _clientID = config["paypal:clientId"];
            _secretID = config["paypal:clientSecret"];
        }
        public IActionResult ReloadCountTotal()
        {
            return ViewComponent("CountCartTotal");
        }
        public IActionResult ReloadDisplayCartTotal()
        {
            return ViewComponent("DisplayCartTotal");
        }
        #region Các chức năng hiển thị = partial view, view components
        public JsonResult ItemToJson(string s)
        {
            var list = _context.ProductTable.Where(x => x.ProductName.StartsWith(s)).ToList();
            return Json(list);
        }

        public IActionResult SingleItemToToModal(int id)
        {
            var returnItem = _context.ProductTable.Find(id);
            return PartialView("_ShowModal", returnItem);
        }

        public IActionResult SingleItemToJson(int id)
        {
            var returnItem = _context.ProductTable.Find(id);
            return Json(returnItem);
        }
        [Authorize]
        public JsonResult GetAddressInfo(int addressValue)
        {
            string userID = _cookieServices.ReadCookie(HttpContext, "CART_INFORMATION");
            var returnItem = _context.DeliveryInfoTable.Single(x => x.User.Id == userID && x.AddressValue == addressValue);
            return Json(returnItem);
        }
        #endregion

        public IActionResult Index()
        {
            return View();
        }
        #region Chức năng Sort,Hiển thị danh sách SP, Trang giỏ hàng
        public IActionResult DisplayProduct(int id = 1)
        {
            return ViewComponent("DisplayProducts", new { currentPage = id });
        }

        public PartialViewResult SortPriceAsc()
        {
            return PartialView("ProductView/_ShowProduct", _context.SortPriceAsc());
        }
        public PartialViewResult SortNameAsc()
        {
            return PartialView("ProductView/_ShowProduct", _context.SortNameAsc());
        }
        [Authorize]
        public PartialViewResult DisplayCart()
        {
            var dsdonhangchuathanhtoan = _context.DisplayCart(HttpContext, _cookieServices);
            return PartialView("ProductView/_ShowCart", dsdonhangchuathanhtoan);
        }
        #endregion

        public IActionResult About()
        {

            return View();
        }

        [Authorize]
        public IActionResult AddCart(int itemID, string size, byte quantity)
        {
            if (_context.AddToCart(HttpContext, itemID, size, quantity))
            {
                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Error));
        }

        [Authorize]
        public IActionResult RemoveCart(int itemID, string size, byte quantity = 1)
        {
            if (_context.RemoveFromCart(HttpContext, itemID, size, quantity))
            {
                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Error));
        }

        #region Thanh toán COD
        [Authorize]
        [HttpPost]
        public IActionResult CodCheckout(string id, bool? usePoint = false)
        {
            try
            {
                var giohangthanhtoanthanhcong = _context.CartTable.Find(id).IsCOD = true;
                _context.SaveChanges();

                var totalPrice = _context.CartDetailTable.Where(x => x.CartID == id).Include(x => x.Product).Sum(x => x.Product.ProductPrice * x.Quantity);
                var user = _userManager.Users.Include(x => x.DeliveryInfo).SingleAsync(x => x.Id == _cookieServices.ReadCookie(HttpContext, "CART_INFORMATION")).Result;
                var pointLeft = user.Point;


                if (usePoint == true && user.Point > 0)
                {
                    if (user.Point <= totalPrice)
                    {
                        pointLeft = 0;
                    }
                    else
                    {
                        pointLeft = (user.Point - Convert.ToInt32(totalPrice));
                    }
                }
                return Redirect(Url.Action(nameof(CheckoutSuccess), "Home", new { id = id, userid = user.Id, pointLeft = pointLeft }, protocol: Request.Scheme));
            }
            catch (HttpException e)
            {
                return RedirectToAction(nameof(CheckoutFail));
            }
        }
        #endregion

        #region Thanh toán Paypal
        [Authorize]
        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> CheckoutAsync(string id, int? addressValue, bool? usePoint = false)
        {
            var environment = new SandboxEnvironment(_clientID, _secretID);
            var client = new PayPalHttpClient(environment);

            var itemList = new ItemList()
            {
                Items = new List<Item>()
            };

            //Query tính tổng giá của đơn hàng bằng cách lặp rồi tính sum của giá * số lượng
            //Nếu cart được tìm thuộc giỏ hàng đang hiển thị thì mới gọi paypal tránh hiện tượng user nhập lại id cũ đã thanh toán nhưng vẫn gọi api paypal
            if (_context.CartTable.Find(id).IsDisplay == true)
            {

                var totalPrice = _context.CartDetailTable.Where(x => x.CartID == id).Include(x => x.Product).Sum(x => x.Product.ProductPrice * x.Quantity);
                var cartItem = _context.CartDetailTable.Where(x => x.CartID == id).Include(x => x.Product);
                //Free ship 15$
                var saleOff = 15;
                var user = await _userManager.Users.Include(x => x.DeliveryInfo).SingleAsync(x => x.Id == _cookieServices.ReadCookie(HttpContext, "CART_INFORMATION"));
                var pointLeft = user.Point;
                var orderAmount = new Amount()
                {
                    Total = (totalPrice - saleOff).ToString(),
                    Currency = "USD",
                    Details = new AmountDetails
                    {
                        Tax = "0",
                        Shipping = "0",
                        ShippingDiscount = saleOff.ToString(),
                        Subtotal = totalPrice.ToString()
                    }
                };
                if (usePoint == true && user.Point > 0)
                {
                    if (user.Point <= totalPrice)
                    {
                        Item point = new Item { Name = "Xu", Currency = "USD", Price = (-user.Point).ToString(), Quantity = "1", Description = $"Sử dụng {user.Point} xu " };
                        itemList.Items.Add(point);
                        orderAmount.Details.Subtotal = (Convert.ToInt32(orderAmount.Details.Subtotal) - user.Point).ToString();
                        orderAmount.Total = (Convert.ToInt32(orderAmount.Total) - user.Point).ToString();
                        pointLeft = 0;
                    }
                    else
                    {
                        Item point = new Item { Name = "Xu", Currency = "USD", Price = (-user.Point).ToString(), Quantity = user.Point.ToString(), Description = $"Sử dụng {totalPrice} xu để giảm giá" };
                        itemList.Items.Add(point);
                        orderAmount.Details.ShippingDiscount = "0";
                        orderAmount.Details.Subtotal = (Convert.ToInt32(orderAmount.Details.Subtotal) - user.Point).ToString();
                        orderAmount.Total = (Convert.ToInt32(orderAmount.Total) - user.Point).ToString();
                        pointLeft = (user.Point - Convert.ToInt32(totalPrice));
                    }
                }

                foreach (var item in cartItem)
                {
                    itemList.Items.Add(new Item()
                    {
                        Name = item.Product.ProductName,
                        Currency = "USD",
                        Price = (item.Product.ProductPrice).ToString(),
                        Quantity = item.Quantity.ToString()
                    });
                }

                if (addressValue >= 1 && addressValue <= 2)
                {
                    itemList.ShippingAddress = new ShippingAddress { City = user.DeliveryInfo.Single(x => x.AddressValue == addressValue).Address, Phone = user.DeliveryInfo.Single(x => x.AddressValue == addressValue).Phone, CountryCode = "VN", Line1 = "Q.10", Line2 = "Sư Vạn Hạnh", State = user.DeliveryInfo.Single(x => x.AddressValue == addressValue).Address, RecipientName = user.UserName, PostalCode = "70000" };
                    itemList.ShippingPhoneNumber = user.DeliveryInfo.Single(x => x.AddressValue == addressValue).Phone;
                }

                var payment = new Payment()
                {
                    Intent = "sale",
                    Transactions = new List<Transaction>()
                {
                    new Transaction()
                    {
                        Amount = orderAmount,

DoAnTMDT/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<title>About</title>

<!-- Content page -->
<section class="bg0 p-t-75 p-b-120">
    <div class="container">
        <div class="row p-b-148">
            <div class="col-md-7 col-lg-8">
                <div class="p-t-7 p-r-85 p-r-15-lg p-r-0-md">
                    <h3 class="mtext-111 cl2 p-b-16">
                        Our Story
                    </h3>

                    <p class="stext-113 cl6 p-b-26">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris consequat consequat enim, non auctor massa ultrices non. Morbi sed odio massa. Quisque at vehicula tellus, sed tincidunt augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas varius egestas diam, eu sodales metus scelerisque congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas gravida justo eu arcu egestas convallis. Nullam eu erat bibendum, tempus ipsum eget, dictum enim. Donec non neque ut enim dapibus tincidunt vitae nec augue. Suspendisse potenti. Proin ut est diam. Donec condimentum euismod tortor, eget facilisis diam faucibus et. Morbi a tempor elit.
                    </p>

                    <p class="stext-113 cl6 p-b-26">
                        Donec gravida lorem elit, quis condimentum ex semper sit amet. Fusce eget ligula magna. Aliquam aliquam imperdiet sodales. Ut fringilla turpis in vehicula vehicula. Pellentesque congue ac orci ut gravida. Aliquam erat volutpat. Donec iaculis lectus a arcu facilisis, eu sodales lectus sagittis. Etiam pellentesque, magna vel dictum rutrum, neque justo eleifend elit, vel tincidunt erat arcu ut sem. Sed rutrum, turpis ut commodo efficitur, quam velit convallis ipsum, et maximus enim ligula ac ligula.
                    </p>

                    <p class="stext-113 cl6 p-b-26">
                        Any questions? Let us know in store at 8th floor, 379 Hudson St, New York, NY 10018 or call us on (+1) 96 716 6879
                    </p>
                </div>
            </div>

            <div class="col-11 col-md-5 col-lg-4 m-lr-auto">
                <div class="how-bor1 ">
                    <div class="hov-img0">
                        <img src="~/images/about-01.jpg" alt="IMG">
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="order-md-2 col-md-7 col-lg-8 p-b-30">
                <div class="p-t-7 p-l-85 p-l-15-lg p-l-0-md">
                    <h3 class="mtext-111 cl2 p-b-16">
                        Our Mission
                    </h3>

                    <p class="stext-113 cl6 p-b-26">
                        Mauris non lacinia magna. Sed nec lobortis dolor. Vestibulum rhoncus dignissim risus, sed consectetur erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam maximus mauris sit amet odio convallis, in pharetra magna gravida. Praesent sed nunc fermentum mi molestie tempor. Morbi vitae viverra odio. Pellentesque ac velit egestas, luctus arcu non, laoreet mauris. Sed in ipsum tempor, consequat odio in, porttitor ante. Ut mauris ligula, volutpat in sodales in, porta non odio. Pellentesque tempor urna vitae mi vestibulum, nec venenatis nulla lobortis. Proin at gravida ante. Mauris auctor purus at lacus maximus euismod. Pellentesque vulputate massa ut nisl hendrerit, eget elementum libero iaculis.
                    </p>

                    <div class="bor16 p-l-29 p-b-9 m-t-22">
                        <p class="stext-114 cl6 p-r-40 p-b-11">
                            Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while.
                        </p>

                        <span class="stext-111 cl8">
                            - Steve Job’s
                        </span>
                    </div>
                </div>
            </div>

            <div class="order-md-1 col-11 col-md-5 col-lg-4 m-lr-auto p-b-30">
                <div class="how-bor2">
                    <div class="hov-img0">
                        <img src="~/images/about-02.jpg" alt="IMG">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="~/vendor/select2/select2.min.js"></script>
<script>$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})</script>
<!--===============================================================================================-->
<script src="~/vendor/MagnificPopup/jquery.magnific-popup.min.js"></script>
<!--===============================================================================================-->
<script src="~/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script>$('.js-pscroll').each(function(){
			$(this).css('position','relative');
			$(this).css('overflow','hidden');
			var ps = new PerfectScrollbar(this, {
				wheelSpeed: 1,
				scrollingThreshold: 1000,
				wheelPropagation: false,
			});

			$(window).on('resize', function(){
				ps.update();
            })
            });

</script>	

DoAnTMDT/Views/Home/Checkout.cshtml
@{
    ViewData["Title"] = "Checkout";
}

<h1>Checkout</h1>

@ViewBag.ID

DoAnTMDT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Trang Chủ - Đồ Án TMĐT";
}

<div class="p-b-10">
    <h3 class="ltext-103 cl5">
        Product Overview
    </h3>
</div>

<div class="flex-w flex-sb-m p-b-52">

    <div class="flex-w flex-l-m filter-tope-group m-tb-10">
        <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter="name" data-order="asc">
            Sort by Name
        </button>

        <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter="price" data-order="asc">
            Sort by Price
        </button>
    </div>

    <div class="flex-w flex-c-m m-tb-10">
        <div class="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search">
            <i class="icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search"></i>
            <i class="icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
            Search
        </div>
    </div>

    <!-- Search product -->
    <div class="dis-none panel-search w-full p-t-10 p-b-15">
        <div class="bor8 dis-flex p-l-15">
            <button class="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04">
                <i class="zmdi zmdi-search"></i>
            </button>

            <input class="mtext-107 cl2 size-114 plh2 p-r-15" type="text" id="select" name="search-product" placeholder="Search">
        </div>
    </div>
</div>

<div class="row isotope-grid">
    @{
        @await Component.InvokeAsync("DisplayProducts")
    }
</div>



<div class="wrap-modal1 js-modal1 p-t-60 p-b-20">
    <div id="ModalArea"></div>
</div>

<!-- Load more -->
<div class="flex-c-m flex-w w-full p-t-45">
    <a id="loadmoreBtn" href="#" class="flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04">
        Load More
    </a>
</div>



@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js" integrity="sha512-HWlJyU4ut5HkEj0QsK/IxBCY55n5ZpskyjVlAoV9Z7XQwwkqXoYdCIC93/htL3Gu5H3R4an/S0h2NXfbZk3g7w==" crossorigin="anonymous"></script>

    <script>
        $(function () {
            if (window.location.href.indexOf("ReturnUrl") > -1) {
                $("#loginBtn").click();
            }

            @if(TempData["CheckoutSuccess"] != null && (bool)TempData["CheckoutSuccess"] == true)
            {
                <text>Swal.fire('Thanh toán thành công', "Bạn đã thành công trong việc tốn tiền một cách lãng phí", "success");</text>
            }

            $("#select").typeahead({
            minLength: 3,
                source: function (request, response) {
                    $.ajax({
                    url: "@Url.Action("ItemToJson", "Home")",
                        data: {
                        "s": request
                        },
                        type: "GET",
                        contentType: "json",
                        success: function (data) {
                        items = [];
                        map = {};
                            $.each(data, function (i, item) {
                            items.push(item);
                        });
                    response(items);
                },
                        error: function (response) {
                    alert(response.responseText);
                },
                        failure: function (response) {
                    alert(response.responseText);
                }
            });
                },
                highlighter: Object,
                displayText: function (item) {
            let imgPath = item.imagePath.replace("~/", "");
            return `<img src="${imgPath}" class="w-25"/>` + '<span class="dropdown-item-extra ml-4 stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6 name">' + item.productName + '</span>'
                },
                afterSelect: function (data) {
                    $("#select").val(data.productName).change();
        }
            });
            //Sự kiện click của nút loadmore khi bấm vào sẽ gửi html trả về vào isotome-grid
            //isotome-grid là container chứa các isotome-item
            var currentPage = 1;
            $('#loadmoreBtn').click(function (e) {
                $.post("@Url.Action("DisplayProduct", "Home")", { "id": currentPage + 1 },
                    function (data) {
                        currentPage++;
                        var $topeContainer = $('.isotope-grid');
                        var $content = $(data);
                        $content.imagesLoaded(function () {
                        $topeContainer.append($content).isotope('insert', $content);
                        });
                    });
                e.preventDefault();
            });
            //sự kiện scroll tham khảo từ : https://dev.to/sakun/a-super-simple-implementation-of-infinite-scrolling-3pnd
            var recentScroll = false;
            $(window).on("scroll", function () {
                //get vị trí scroll hiện tại và vị trí của scroll hiện tại so với đỉnh màn hình
                var scrollHeight = $(document).height();
                var scrollPos = $(window).height() + $(window).scrollTop();
                //sự kiện sẽ xảy ra khi cách đáy browser 500px
                if (((scrollHeight - 500) >= scrollPos) / scrollHeight == 0 && !recentScroll) {
                    $('#loadmoreBtn').click();

                    recentScroll = true;
                    window.setTimeout(() => { recentScroll = false; }, 3000)
                }
            });
    });
    </script>
} 